export const APP = {
	REQUEST_APP_INITIALIZE: 'REQUEST_APP_INITIALIZE',
    APPLICATION_INITIALIZE_SUCCEEDED: 'APPLICATION_INITIALIZE_SUCCEEDED',
    APPLICATION_INITIALIZE_FAILED: 'APPLICATION_INITIALIZE_FAILED',
    SCHEMA_LOADED: 'SCHEMA_LOADED',
    FIELD_CREATED: 'FIELD_CREATED',
};

export const RULE_CHECK = {
	REQUEST_RULE_CHECK: 'REQUEST_RULE_CHECK',
	RULE_CHECK_SUCCEEDED: 'RULE_CHECK_SUCCEEDED',
	RULE_CHECK_FAILED: 'RULE_CHECK_FAILED',
};

export const FILE = {
	REQUEST_EXPORT_FILE: 'REQUEST_EXPORT_FILE',
	EXPORT_FILE_SUCCEEDED: 'EXPORT_FILE_SUCCEEDED',
	EXPORT_FILE_FAILED: 'EXPORT_FILE_FAILED',
};
