export const APP = {
	REQUEST_LOAD_SCHEMA_FILE: 'REQUEST_LOAD_SCHEMA_FILE',
	LOAD_SCHEMA_FILE_SUCCEEDED: 'LOAD_SCHEMA_FILE_SUCCEEDED',
	LOAD_SCHEMA_FILE_FAILED: 'LOAD_SCHEMA_FILE_FAILED',
};

export const RULE_CHECK = {
	REQUEST_RULE_CHECK: 'REQUEST_RULE_CHECK',
	RULE_CHECK_SUCCEEDED: 'RULE_CHECK_SUCCEEDED',
	RULE_CHECK_FAILED: 'RULE_CHECK_FAILED',
};

export const FILE = {
	REQUEST_EXPORT_FILE: 'REQUEST_EXPORT_FILE',
	EXPORT_FILE_SUCCEEDED: 'EXPORT_FILE_SUCCEEDED',
	EXPORT_FILE_FAILED: 'EXPORT_FILE_FAILED',
};
